'use client'

import Link from 'next/link'
import React from 'react'
import { ArrowRight, Check, Mail, Heart, Trash2 } from 'lucide-react'
import { Footer, ProductGrid, SiteHeader, Quantity, useStore } from '@/components/store'
import { blogPosts, money, products } from '@/lib/catalog'

export function CartPage() { const { cart, removeFromCart, updateQuantity } = useStore(); const subtotal = cart.reduce((sum, item) => sum + item.product.price * item.quantity, 0); return <><SiteHeader /><main className="page-shell narrow"><div className="page-intro left"><p className="eyebrow">Your selection</p><h1>Shopping bag</h1><p>{cart.length} items · Complimentary shipping over $150</p></div><div className="cart-layout">{cart.length ? <div className="cart-list">{cart.map(({ product, quantity, size }) => <div className="cart-row" key={product.id}><img src={product.image} alt={product.name} /><div className="cart-row-copy"><p className="eyebrow">{product.category}</p><h3>{product.name}</h3><p>Size {size || 'Standard'}</p><div className="cart-row-bottom"><span>{money(product.price * quantity)}</span><Quantity value={quantity} onChange={(value) => updateQuantity(product.id, value)} /></div></div><button className="remove" onClick={() => removeFromCart(product.id)} aria-label={`Remove ${product.name}`}><Trash2 size={16} /> Remove</button></div>)}</div> : <div className="empty-state"><h2>Your bag is quiet.</h2><p>Discover something considered for the season.</p><Link href="/shop" className="button button-dark">Shop new arrivals <ArrowRight size={15} /></Link></div>}<aside className="summary"><h3>Summary</h3><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div><span>Shipping</span><strong>{subtotal >= 150 ? 'Free' : '$12.00'}</strong></div><div className="summary-total"><span>Total</span><strong>{money(subtotal >= 150 ? subtotal : subtotal + 12)}</strong></div><Link href={cart.length ? '/checkout' : '/shop'} className="button button-dark full">{cart.length ? 'Checkout' : 'Continue shopping'} <ArrowRight size={15} /></Link><p className="secure-note">Secure checkout · Visa · Mastercard · Mobile money</p></aside></div></main><Footer /></> }

export function CheckoutPage() { const { cart } = useStore(); const [method, setMethod] = React.useState('mobile-money'); const total = cart.reduce((sum, item) => sum + item.product.price * item.quantity, 0); return <><SiteHeader /><main className="page-shell narrow"><div className="page-intro left"><p className="eyebrow">Almost there</p><h1>Checkout</h1></div><div className="checkout-layout"><form className="checkout-form" onSubmit={(event) => event.preventDefault()}><div className="checkout-section"><h3>Contact information</h3><input placeholder="Email address" type="email" required /><label className="checkbox"><input type="checkbox" /> Email me with news and offers</label></div><div className="checkout-section"><h3>Shipping address</h3><div className="input-grid"><input placeholder="First name" required /><input placeholder="Last name" required /></div><input placeholder="Address" required /><div className="input-grid three"><input placeholder="City" required /><input placeholder="State" required /><input placeholder="ZIP code" required /></div></div><div className="checkout-section"><h3>Payment method</h3><div className="payment-methods"><button type="button" className={method === 'mobile-money' ? 'payment-option active' : 'payment-option'} onClick={() => setMethod('mobile-money')}><span className="payment-logo">M</span><span><strong>Mobile money</strong><small>Pay with your mobile wallet</small></span><span className="payment-radio" /></button><button type="button" className={method === 'card' ? 'payment-option active' : 'payment-option'} onClick={() => setMethod('card')}><span className="payment-logo card-logo">▣</span><span><strong>Card payment</strong><small>Visa, Mastercard, or Amex</small></span><span className="payment-radio" /></button></div>{method === 'mobile-money' ? <div className="mobile-money-fields"><label>Network<select defaultValue="MTN"><option>MTN Mobile Money</option><option>Vodafone Cash</option><option>AirtelTigo Money</option></select></label><label>Mobile money number<input placeholder="024 000 0000" type="tel" /></label><p>We will send a secure payment prompt to this number.</p></div> : <div className="mobile-money-fields"><label>Card number<input placeholder="1234 5678 9012 3456" inputMode="numeric" /></label><div className="input-grid"><input placeholder="MM / YY" /><input placeholder="CVC" /></div></div>}</div><button className="button button-dark full" type="submit">Place order <ArrowRight size={15} /></button></form><div className="checkout-order"><h3>Order summary</h3>{cart.map(({ product, quantity }) => <div className="mini-order" key={product.id}><img src={product.image} alt="" /><span>{product.name} × {quantity}</span><strong>{money(product.price * quantity)}</strong></div>)}<div className="summary-total"><span>Total</span><strong>{money(total)}</strong></div></div></div></main><Footer /></> }

export function WishlistPage() { const { wishlist } = useStore(); const saved = products.filter((product) => wishlist.includes(product.id)); return <><SiteHeader /><main className="page-shell"><div className="page-intro"><p className="eyebrow">Saved for later</p><h1>Wishlist</h1><p>{saved.length ? 'Your considered edit of pieces to come back to.' : 'Tap the heart on any piece to save it here.'}</p></div>{saved.length ? <ProductGrid items={saved} /> : <div className="empty-state centered"><HeartIcon /><Link href="/shop" className="button button-dark">Explore the collection <ArrowRight size={15} /></Link></div>}</main><Footer /></> }
function HeartIcon() { return <span className="empty-heart">♡</span> }

export function AccountPage() { return <><SiteHeader /><main className="page-shell narrow account-page"><div className="page-intro"><p className="eyebrow">Welcome back</p><h1>Account</h1><p>Sign in to view orders and save your details.</p></div><form className="auth-card"><input type="email" placeholder="Email address" /><input type="password" placeholder="Password" /><button className="button button-dark full">Sign in <ArrowRight size={15} /></button><Link href="#" className="center-link">Forgot password?</Link><div className="auth-divider"><span>or</span></div><button type="button" className="outline-button full">Create an account</button></form></main><Footer /></> }

export function BlogPage() { return <><SiteHeader /><main className="page-shell"><div className="page-intro"><p className="eyebrow">From the studio</p><h1>Journal</h1><p>Stories about style, materials, and making space for the good things.</p></div><div className="blog-grid">{blogPosts.map((post) => <article className="blog-card" key={post.slug}><Link href={`/blog/${post.slug}`}><img src={post.image} alt={post.title} /></Link><p className="eyebrow">{post.category} · {post.date}</p><h2><Link href={`/blog/${post.slug}`}>{post.title}</Link></h2><p>{post.excerpt}</p><Link href={`/blog/${post.slug}`} className="text-link">Read story <ArrowRight size={14} /></Link></article>)}</div></main><Footer /></> }

export function ContactPage() { return <><SiteHeader /><main className="page-shell contact-page"><div className="contact-intro"><p className="eyebrow">We would love to hear from you</p><h1>Questions,<br /><em>ideas, hello.</em></h1><p>Our team is here Monday through Friday, 9am–5pm EST. We usually reply within one business day.</p><a href="mailto:hello@mixtas.studio" className="text-link">hello@mixtas.studio <ArrowRight size={14} /></a></div><form className="contact-form"><label>Your name<input placeholder="Name" /></label><label>Email address<input type="email" placeholder="Email" /></label><label>How can we help?<textarea placeholder="Tell us a little more" rows={5} /></label><button className="button button-dark">Send message <ArrowRight size={15} /></button></form></main><Footer /></> }

